version: '3'
services:
  mysql-container:
    build: ./mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=contacts_db
      - MYSQL_ROOT_PASSWORD=iseveShare4rce.

  node-app:
    build: ./node-app
    ports:
      - "30594:30594"

  react:
    build: ./react
    ports:
      - "3000:3000"
